apiVersion: v1
kind: Pod
metadata:
  name: active-incident-dev
  labels:
    app.kubernetes.io/name: active-incident
spec:
  volumes:
    - name: active-incident-data-volume
      persistentVolumeClaim:
        claimName: active-incident-storage
        readOnly: false
  containers:
    - name: active-incident-container
      image: us-central1-docker.pkg.dev/mchirico/public/activeincident:v0.1.2
      env:
      - name: MONGO_URI
        valueFrom:
          secretKeyRef:
            name: mongo-creds
            key: mongouri
# These are test values: see /workspaces/k8s_gcp/mongodb-notes/secrets/activeIncident
      - name: MONGO_DB
        valueFrom:
          secretKeyRef:
            name: mongo-creds
            key: mongotestdatabase
# These are test values: see /workspaces/k8s_gcp/mongodb-notes/secrets/activeIncident
      - name: MONGO_COLLECTION
        valueFrom:
          secretKeyRef:
            name: mongo-creds
            key: mongotestcollection

      - name: OWM_API_KEY
        valueFrom:
          secretKeyRef:
            name: mongo-creds
            key: weatherkey

      - name: MONGO_WEATHER
        valueFrom:
          secretKeyRef:
            name: mongo-creds
            key: weathertestcollection


      volumeMounts:
        - mountPath: /etc/mongo
          name: active-incident-data-volume
  restartPolicy: Always
