apiVersion: v1
kind: Pod
metadata:
  name: septa-incident
  labels:
    app.kubernetes.io/name: septa-incident
spec:
  volumes:
    - name: septa-incident-data-volume
      persistentVolumeClaim:
        claimName: septa-incident-storage
        readOnly: true
  containers:
    - name: septa-incident-container
      image: us-central1-docker.pkg.dev/mchirico/public/septa:v0.0.1
      env:
      - name: MONGO_URI
        valueFrom:
          secretKeyRef:
            name: mongo-creds
            key: mongouri

      - name: OWM_API_KEY
        valueFrom:
          secretKeyRef:
            name: mongo-creds
            key: weatherkey

      - name: MONGO_WEATHER
        valueFrom:
          secretKeyRef:
            name: mongo-creds
            key: weathercollection


      volumeMounts:
        - mountPath: /etc/mongo
          name: septa-incident-data-volume
  restartPolicy: Always
