apiVersion: v1
kind: Service
metadata:
  name: septa-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.0.0.0
  selector:
    app.kubernetes.io/name: septa-service
  ports:
    - protocol: TCP
      port: 443
      targetPort: 2379
