apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mongo-storage
spec:
   storageClassName: mongo-storage-class
   accessModes:
     - ReadWriteOnce
   resources:
     requests:
       storage: 20Gi
